# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_auto_20181109_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
