# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0005_user_addtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=5)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myhome.User')),
            ],
        ),
    ]
