# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0007_class_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=32)),
                ('cid', models.ManyToManyField(to='myhome.Classs')),
            ],
        ),
    ]
