# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_classes_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addtime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
